
CREATE TABLE MOVE_TYPE(
  ID INT AUTO_INCREMENT  PRIMARY KEY,  
  MOVE_TYPE VARCHAR(250) NOT NULL UNIQUE
);


CREATE TABLE ANIMAL_TYPE(
  ID INT AUTO_INCREMENT  PRIMARY KEY,  
  ANIMAL_TYPE VARCHAR(250) NOT NULL UNIQUE
);

CREATE TABLE ANIMAL(
  ID INT AUTO_INCREMENT  PRIMARY KEY,
  NAME VARCHAR(250) NOT NULL UNIQUE,
  MOVE_TYPE INT,
  ANIMAL_TYPE INT,
FOREIGN KEY (ANIMAL_TYPE) REFERENCES ANIMAL_TYPE(ID),
FOREIGN KEY (MOVE_TYPE) REFERENCES MOVE_TYPE(ID)

);



INSERT INTO ANIMAL_TYPE(ANIMAL_TYPE) VALUES
  ('Bird'),('Fish'),('Human'),('Snake'),('Kangaroo');

INSERT INTO MOVE_TYPE(MOVE_TYPE) VALUES
  ('Fly'),('Swim'),('Walk'),('Slither'),('Hop');
